---

- hosts: local
  become: yes
  become_user: root
  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 86400
  roles:
    - role: system-backup
