---

# Tilix gnome
- name: Force remove dconf.txt
  file:
    path: "/home/{{ username }}/{{ mconf }}/{{ backup_location }}/dconf.txt"
    state: absent
  when: nuke|bool

- name: Get dconf dump
  command: "dconf dump /"
  args:
    creates: "/home/{{ username }}/{{ mconf }}/{{ backup_location }}/dconf.txt"
  register: dump

- name: Create dconf.txt
  copy: 
    content: "{{ dump.stdout }}"
    dest: "/home/{{ username }}/{{ mconf }}/{{ backup_location }}/dconf.txt"
  when: dump.changed

- name: Remove useless lines from dconf.txt
  lineinfile:
    path: "/home/{{ username }}/{{ mconf }}/{{ backup_location }}/dconf.txt"
    state: absent
    regexp: "{{ item }}"
  with_items:
    - virtual-root
    - last-save-directory

# Tilix settings
- name: Force remove tilix.txt
  file:
    path: "/home/{{ username }}/{{ mconf }}/{{ backup_location }}/dconf.txt"
    state: absent
  when: nuke|bool
  tags: [tilix]

- name: Get tilix dump
  command: "dconf dump /com/gexperts/Tilix/"
  args:
    creates: "/home/{{ username }}/{{ mconf }}/{{ backup_location }}/tilix.txt"
  register: dump
  tags: [tilix]

- name: Create tilix.txt
  copy: 
    content: "{{ dump.stdout }}"
    dest: "/home/{{ username }}/{{ mconf }}/{{ backup_location }}/tilix.txt"
  when: dump.changed
  tags: [tilix]
