---

- name: Get dconf dump
  command: "dconf dump /"
  args:
    creates: "/home/{{ username }}/{{ mconf }}/{{ backup_location }}/dconf.txt"
  register: dump

- name: Create dconf.txt
  copy: 
    content: "{{ dump.stdout }}"
    dest: "/home/{{ username }}/{{ mconf }}/{{ backup_location }}/dconf.txt"
  when: dump.changed

- name: Remove useless lines from dconf.txt
  lineinfile:
    path: "/home/{{ username }}/{{ mconf }}/{{ backup_location }}/dconf.txt"
    state: absent
    regexp: "{{ item }}"
  with_items:
    - virtual-root
    - last-save-directory