---

- name: Create backups folder
  file:
    path: "/home/{{ username }}/{{ mconf }}/{{ backup_location }}/"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755
  tags: [initialize]

- name: Create cache folder
  file:
    path: "/home/{{ username }}/{{ mconf }}/{{ backup_location }}/.cache/"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755
  tags: [initialize]
