---

- name: Create cache folder
  file:
    path: "/home/{{ username }}/{{ mconf }}/{{ backup_location }}/"
    state: "{{ item }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755
  loop:
    - absent
    - directory

- name: Create cache folder
  file:
    path: "/home/{{ username }}/{{ mconf }}/{{ backup_location }}/.cache/"
    state: "{{ item }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755
  loop:
    - absent
    - directory
