---

- import_tasks: initialize.yml
  tags: [initialize]

- import_tasks: vscode.yml
  become_user: "{{ username }}"
  tags: [vscode]

- import_tasks: dconf.yml
  become_user: "{{ username }}"
  tags: [dconf, tilix]

- name: Copy `autostart/`
  become_user: "{{ username }}"
  copy:
    src: "/home/{{ username }}/.config/autostart/"
    dest: "/home/{{ username }}/{{ mconf }}/{{ backup_location }}/autostart/"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644
  tags: [autostart]

- name: End note
  vars:
    msg: |
         Remember to backup:-
          1. Documents
          2. Downloads
          3. Code(Git)
         Remember to Check :-
          1. Potentially sensitive data is removed
         Complete!
  debug:
    msg: "{{ msg.split('\n') }}"
