---

- import_tasks: initialize.yml

- import_tasks: vscode.yml
  become_user: "{{ username }}"

- import_tasks: system.yml
  become_user: "{{ username }}"

- name: End note
  pause:
    prompt: |
      Remember to backup:-
        1. Documents
        2. Downloads
        3. Code(Git)
      Remember to Check :-
        1. Potentially sensitive data is removed
      Complete!
