---
- name: Ensure required directories exist
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: "{{ username }}"
    group: "{{ username }}"
  with_items:
    - "/home/{{ username }}/{{ mconf }}/{{ backup_location }}/"
    - "/home/{{ username }}/{{ mconf }}/{{ backup_location }}/.cache/"
    - "/home/{{ username }}/{{ mconf }}/{{ backup_location }}/dotfiles/"
    - "/home/{{ username }}/{{ mconf }}/{{ backup_location }}/vscode/"
    - "/home/{{ username }}/{{ mconf }}/{{ private_backup_location }}/"
    - "/home/{{ username }}/{{ mconf }}/{{ private_backup_location }}/.cache/"

- import_tasks: vscode.yml
  tags: [always]

- import_tasks: system.yml
  tags: [always]

- import_tasks: flavour-i3wm.yml
  when: "'i3wm' in ansible_run_tags"
  tags: [i3wm]

- name: End note
  pause:
    prompt: |
      Remember to backup:-
        1. Documents
        2. Downloads
        3. Code(Git)
      Remember to Check :-
        1. Potentially sensitive data is removed
      Complete!
