- name: Copy configuration files
  become: yes
  copy:
    src: "{{ item.src  }}"
    dest: "{{ item.dest }}"
    owner: "{{ username  }}"
    group: "{{ username  }}"
    mode: 0644
  with_items:
    - {
        src: "/home/{{ username }}/.bashrc",
        dest: "/home/{{ username }}/{{ mconf }}/{{ backup_location }}/dotfiles/.bashrc.raspi",
      }
