---
- name: Copy common configurations
  become: yes
  copy:
    src: "{{ item.src  }}"
    dest: "{{ item.dest }}"
    owner: "{{ username  }}"
    group: "{{ username  }}"
    mode: 0644
    directory_mode: 0755
  with_items:
    - {
        src: "/home/{{ username }}/.Xdefaults",
        dest: "/home/{{ username }}/{{ mconf }}/{{ backup_location }}/dotfiles/.Xdefaults",
      }
    - {
        src: "/home/{{ username }}/.vimrc",
        dest: "/home/{{ username }}/{{ mconf }}/{{ backup_location }}/dotfiles/.vimrc",
      }
    - {
        src: "/etc/default/grub",
        dest: "/home/{{ username }}/{{ mconf }}/{{ backup_location }}/dotfiles/grub",
      }
    - {
        src: "/home/{{ username }}/.config/autostart",
        dest: "/home/{{ username }}/{{ mconf }}/{{ backup_location }}/dotfiles/",
      }

- include_tasks: cache-copy.yml
  vars:
    src_filefolder: "/home/{{ username }}"
    filename: "{{ item }}"
  with_items:
    - ".bashrc"
    - ".bash_profile"

- name: Copy Keyrings
  copy:
    src: "/home/{{ username }}/.local/share/keyrings/"
    dest: "/home/{{ username }}/{{ mconf }}/{{ private_backup_location }}/keyrings/"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644

- include_tasks: cache-copy.yml
  vars:
    src_filefolder: "/etc"
    filename: "{{ item }}"
  with_items:
    - "hosts"

# Others
- name: Copy SSH
  copy:
    src: "/home/{{ username }}/.ssh/"
    dest: "/home/{{ username }}/{{ mconf }}/{{ private_backup_location }}/ssh/"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644

- name: Copy GPG
  copy:
    src: "/home/{{ username }}/.gnupg/"
    dest: "/home/{{ username }}/{{ mconf }}/{{ private_backup_location }}/gnupg/"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644

- name: Copy Network
  # sudo required for this task,
  # read : https://superuser.com/questions/1522927/ansible-copy-module-become-permission-denied
  become: yes
  become_user: root
  copy:
    src: /etc/NetworkManager/system-connections
    dest: "/home/{{ username }}/{{ mconf }}/{{ private_backup_location }}/"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644

- name: Copy Bluetooth
  # sudo required for this task,
  # read : https://superuser.com/questions/1522927/ansible-copy-module-become-permission-denied
  become: yes
  become_user: root
  copy:
    src: "/var/lib/bluetooth/"
    dest: "/home/{{ username }}/{{ mconf }}/{{ private_backup_location }}/bluetooth/"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644

- name: Copy sudoers
  # sudo required for this task,
  # read : https://superuser.com/questions/1522927/ansible-copy-module-become-permission-denied
  become: yes
  become_user: root
  copy:
    src: /etc/sudoers.d
    dest: "/home/{{ username }}/{{ mconf }}/{{ private_backup_location }}/"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755

- name: Remove unwanted invar/ files and directories
  file:
    path: "/invar/{{ item }}"
    state: absent
  loop:
    - lost+found
    - .Trash-1000

- name: Copy /invar/
  copy:
    src: "/invar/"
    dest: "/home/{{ username }}/{{ mconf }}/{{ private_backup_location }}/invar/"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644
    directory_mode: 0755
