---

- name: Perform apt full-update
  become: yes
  become_user: root
  apt:
    upgrade: full
  notify:
    - apt autoremove
    - apt autoclean
  tags: [raspi, netinst]

- import_tasks: apt-amd-graphics.yml
  become_user: "{{ username }}"

- name: Install all common packages
  become: yes
  become_user: root
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - vim
    - curl
    - network-manager
    - x11-xserver-utils
    - apt-transport-https
    - xclip
    - git
    - make
    - undistract-me
    - firefox-esr
    - chromium
    - vlc
  notify:
    - apt autoremove
    - apt autoclean
  tags: [raspi, netinst]

- name: Install basic i3 requirment packages
  become: yes
  become_user: root
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - i3
    - sudo
    - alsa-utils
    - pulseaudio
    - compton
    - xbacklight
    - rofi
    - xterm
    - nemo
    - xinit
    - xfonts-base
    - xfonts-cyrillic
    - xfonts-100dpi
    - xfonts-75dpi
    - feh
    - flameshot
  notify:
    - apt autoremove
    - apt autoclean
  tags: [raspi, netinst]

- name: make user sudoer
  become: yes
  become_user: root
  user:
    name: "{{ username }}"
    groups: sudo
    append: yes
  notify:
    - reset ssh connection
  tags: [raspi, netinst]

- name: Git global configuration
  git_config:
    name: "{{ item.name }}"
    scope: global
    value: "{{ item.value }}"
  with_items:
    -  { name: user.email, value: "{{ git_email }}" }
    -  { name: user.name, value: "{{ git_name }}" }
    -  { name: core.editor, value: "vi" }
  tags: [raspi, netinst]
