---

- name: Add caffeine repository
  become: yes
  become_user: root
  apt_repository:
    repo: ppa:caffeine-developers/ppa

- name: Update apt cache
  become: yes
  become_user: root
  apt:
    update_cache: yes
    cache_valid_time: 86400

- name: Perform apt full-update
  become: yes
  become_user: root
  apt:
    upgrade: full
  notify:
    - apt autoremove
    - apt autoclean

- name: Install all common packages
  become: yes
  become_user: root
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - curl 
    - apt-transport-https 
    - xclip 
    - git 
    - make
    - dconf-tools
    - undistract-me
    - firefox
    - caffeine
    - vlc
  notify:
    - apt autoremove
    - apt autoclean

- name: Git global configuration
  git_config:
    name: "{{ item.name }}"
    scope: global
    value: "{{ item.value }}" 
  with_items:
    -  { name: user.email, value: "{{ git_email }}" }
    -  { name: user.name, value: "{{ git_name }}" }
