---

- import_tasks: common-apt.yml
  become_user: "{{ username }}"
  tags: [basic]

- import_tasks: python.yml
  become_user: "{{ username }}"
  tags: [python, basic]

- import_tasks: vscode.yml
  become_user: "{{ username }}"
  tags: [vscode, basic]

- import_tasks: spotify.yml
  become: yes
  become_user: root
  tags: [spotify]

- import_tasks: system.yml
  become_user: "{{ username }}"
  tags: [system, basic]
