---

- import_tasks: apt-common.yml
  become_user: "{{ username }}"

- import_tasks: python.yml
  become_user: "{{ username }}"

- import_tasks: vscode.yml
  become_user: "{{ username }}"

- import_tasks: keybase.yml
  become_user: "{{ username }}"

- import_tasks: spotify.yml
  become_user: root

- import_tasks: system.yml
  become_user: "{{ username }}"
