---
- import_tasks: apt-common.yml
  tags: [always]

- import_tasks: python.yml
  tags: [always]

- import_tasks: vscode.yml
  tags: [always]

- import_tasks: spotify.yml
  tags: [always]

- import_tasks: system.yml
  tags: [always]

- import_tasks: flavour-i3wm.yml
  when: "'i3wm' in ansible_run_tags"
  tags: [i3wm]

- import_tasks: flavour-xfce.yml
  when: "'xfce' in ansible_run_tags"
  tags: [xfce]

- import_tasks: raspi.yml
  when: "'raspi' in ansible_run_tags"
  tags: [raspi]

- name: End note
  pause:
    prompt: |
      Remember to Install:-
        1. Opensnitch
        2. Signal
      Remember to Configure:-
        1. To retry fingerprint after first failure, see:  /etc/pam.d/common-auth
      Complete!
