---
- name: Install all common Python packages
  become: yes
  become_user: root
  apt:
    state: latest
    name: "{{ packages }}"
  vars:
    packages:
      - python3
      - python3-pip
      - python3-apt
      - python3-dev
      - build-essential
      - libssl-dev
      - libffi-dev
      - python-is-python3
