---

- name: Install all common Python packages
  become: yes
  become_user: root
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - python3
    - python3-pip
    - build-essential
    - libssl-dev
    - libffi-dev
    - python-dev

- name: Update pip & related tools
  pip:
    name:
      - setuptools
      - autopep8
      - pipenv
      - pip
    state: latest
