---

  - name: Install all common Python packages
    apt:
      name: "{{ packages }}"
    vars:
      packages:
      - python3
      - python3-pip
      - build-essential
      - libssl-dev
      - libffi-dev
      - python-dev
      - python
    notify:
      - apt autoremove
      - apt autoclean

  - name: Update pip & related tools
    pip:
      name:
        - autopep8
        - ipython
        - pipenv
        - pip
      state: latest
