---

- name: Create invar directory
  become: yes
  become_user: root
  file:
    path: /invar/
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755
  tags: [raspi, netinst]

- name: Ensure root dotfiles' directories exists
  become: yes
  become_user: root
  file:
    path:  "{{ item }}"
    state: directory
    mode:  0755
    owner: root
    group: root
  loop:
    - "/etc/default/"
    - "/etc/X11/"
    - "/etc/systemd/system/getty@tty1.service.d/"
  tags: [raspi, netinst]

- name: Ensure user dotfiles' directories exists
  file:
    path:  "{{ item }}"
    state: directory
    mode:  0755
    owner: "{{ username }}"
    group: "{{ username }}"
  loop:
    - "/home/{{ username }}/.config/i3/"
    - "/home/{{ username }}/.jupyter/nbconfig/"
  tags: [raspi, netinst]

- name: Copy runable Scripts
  become: yes
  become_user: root
  copy:
    src:   "{{ item.src  }}"
    dest:  "{{ item.dest }}"
    owner: "{{ item.own  }}"
    group: "{{ item.own  }}"
    mode:  0744
  with_items:
    - {
        src:  "/home/{{ username }}/{{ mconf }}/{{ backup_location }}/i3-mruws.py",
        dest: "/home/{{ username }}/.config/i3/i3-mruws.py",
        own:  "{{ username }}"
      }
  tags: [raspi, netinst]

- name: Copy configuration files
  become: yes
  become_user: root
  copy:
    src:   "{{ item.src  }}"
    dest:  "{{ item.dest }}"
    owner: "{{ item.own  }}"
    group: "{{ item.own  }}"
    mode:  0644
  notify:
    - enable getty@tty1
    - reset ssh connection
  with_items:
    - {
        src:  "/home/{{ username }}/{{ mconf }}/{{ backup_location }}/dotfiles/.Xdefaults",
        dest: "/home/{{ username }}/.Xdefaults",
        own:  "{{ username }}"
      }
    - {
        src:  "/home/{{ username }}/{{ mconf }}/{{ backup_location }}/dotfiles/.bash_profile",
        dest: "/home/{{ username }}/.bash_profile",
        own:  "{{ username }}"
      }
    - {
        src:  "/home/{{ username }}/{{ mconf }}/{{ backup_location }}/dotfiles/i3.config",
        dest: "/home/{{ username }}/.config/i3/config",
        own:  "{{ username }}"
      }
    - {
        src:  "/home/{{ username }}/{{ mconf }}/{{ backup_location }}/dotfiles/compton.conf",
        dest: "/home/{{ username }}/.config/i3/compton.conf",
        own:  "{{ username }}"
      }
    - {
        src:  "/home/{{ username }}/{{ mconf }}/{{ backup_location }}/dotfiles/.vimrc",
        dest: "/home/{{ username }}/.vimrc",
        own:  "{{ username }}"
      }
    - {
        src:  "/home/{{ username }}/{{ mconf }}/{{ backup_location }}/dotfiles/notebook.json",
        dest:   "/home/{{ username }}/.jupyter/nbconfig/notebook.json",
        own:  "{{ username }}"
      }
    - {
        src:  "/home/{{ username }}/{{ mconf }}/{{ backup_location }}/dotfiles/getty.override.conf",
        dest: "/etc/systemd/system/getty@tty1.service.d/override.conf",
        own:  "root"
      }
  tags: [raspi, netinst]

- import_tasks: system-raspi.yml
  become_user: "{{ username }}"

- import_tasks: system-netinst.yml
  become_user: "{{ username }}"

