---
- name: Install vscode
  ignore_errors: yes
  include_role:
    name: gantsign.visual-studio-code
    tasks_from: install
  vars:
    ansible_become: yes
    ansible_become_method: su
    ansible_become_user: root

- name: Install extensions
  include_role:
    name: gantsign.visual-studio-code
    tasks_from: install-extensions
  vars:
    ansible_become: yes
    ignore_errors: yes
    users:
      - username: "{{ username }}"
        visual_studio_code_extensions:
          - esbenp.prettier-vscode
          - ms-python.python
          - ms-vscode-remote.remote-containers
          - ms-vscode-remote.remote-ssh
          # - pranaygp.vscode-css-peek

- name: Copy settings.json
  copy:
    src: "/home/{{ username }}/{{ mconf }}/{{ backup_location }}/vscode/settings.json"
    dest: "/home/{{ username }}/.config/Code/User/"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644

- name: Copy keybindings.json
  copy:
    src: "/home/{{ username }}/{{ mconf }}/{{ backup_location }}/vscode/keybindings.json"
    dest: "/home/{{ username }}/.config/Code/User/"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644
